version: '3'
services:
  www:

    build:
      context: .
      dockerfile: Dockerfile_Web_App
    container_name: www
    ports:
      - 3000:80
      - 443:443 # for future ssl traffic
  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
